Issue 330
karakun/OpenWebStart pull request #331
Opened 2020-10-02 20:50 UTC by r-sreesaran

Added Tests for JsonHandler class

2020-10-02 22:36 UTC, sclassen requested changes
Thank you for this contribution to OpenWebStart !!

Some minor changes are required, mostly formatting.

Also could you please add another test which converts a Person -> Json -> Person and then assert that the age and name are the same as the original.

2020-10-02 22:36 UTC, sclassen commented on openwebstart/src/test/java/com/openwebstart/jvm/json/JsonHandlerTest.java
> +import static org.junit.jupiter.api.Assertions.*;
No star imports please

2020-10-02 22:36 UTC, sclassen commented on openwebstart/src/test/java/com/openwebstart/jvm/json/Person.java
> +    String name;
make fields `private`

2020-10-03 06:46 UTC, r-sreesaran commented on openwebstart/src/test/java/com/openwebstart/jvm/json/JsonHandlerTest.java
> +import static org.junit.jupiter.api.Assertions.*;
done

2020-10-03 16:00 UTC, r-sreesaran commented
requested changes were done.

2020-10-04 14:20 UTC, hendrikebbers commented
This looks quite good in general. One important point is missing here:

Internally the Json handler is used to deserialise the given classes `LocalJavaRuntime`, `RemoteJavaRuntime`, and `RemoteRuntimeList`. Can you add some tests (deserialisation will be enough) for this classes?

2020-10-05 14:36 UTC, r-sreesaran commented
Above mentioned scenarios were covered.

2020-10-11 09:56 UTC, r-sreesaran commented
Anything else pending here ?

2020-10-11 19:52 UTC, sclassen commented
Sorry to have you hanging here.
We are currently looking with legal department if we need a CLA for contributions. Will give you an update on Monday.

2020-10-12 19:09 UTC, sclassen commented
@r-sreesaran
Can you please go to https://dev.karakun.com/cla/ and fill out the appropriate CLA.
Once this is done we can merge this.
Thank you for your patience.

Oh and thank you for being our guinea pig for this process.
You will be the first to do this.

Could you quickly drop a line here once you sent the CLA so we can make sure everything runs smooth.

2020-10-12 19:11 UTC, sclassen approved these changes

2020-10-13 11:03 UTC, r-sreesaran commented
CLA sent.

2020-10-13 11:27 UTC, sclassen commented
@cla-bot check

2020-10-13 11:27 UTC, merged

2020-10-13 11:27 UTC, sclassen commented
Thank you. all worked out fine with the CLA.
Happy to receive more contributions from you  :)